from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.blockchain.block import Block
    from core.blockchain.transaction import BaseTransaction, CoinbaseTransaction
    from core.blockchain.blockchain import Blockchain

class BaseBackend:
    def __init__(self: "Blockchain"): ...

    def add_to_coinbase_queue(self, coinbase_tx: "CoinbaseTransaction", height: int): ...
    def get_coinbase_transaction(self, height: int) -> "CoinbaseTransaction": ...

    def get_balance(self, address: bytes) -> int: ...
    def set_balance(self, address: bytes, amount: int): ...
    def get_address_nonce(self, address: bytes) -> int: ...
    def increment_address_nonce(self, address: bytes): ...
    def set_block(self, block: "Block"): ...
    def get_block(self) -> "Block": ...

    def get_block_reward(self) -> int: ...
    def set_block_reward(self, new_reward: int): ...

    def add_transaction(self, tx: "BaseTransaction"): ...
    def get_transactions(self, sort: str, limit: int) -> list["BaseTransaction"]: ...